### PR TITLE
Added ARM support

### LINKED ISSUE #5: ARM/alternate architecture support
Currently, we only build/test for x86-64. If people are interested, we welcome contributions to add support for alternate architectures (especially ARM).

### PR DESCRIPTION
**Pull request by corentinartaud**
Adds wheel support for `arm64`. The build-publish workflow was also updated to suport `macos_arm64`. Built locally with `pip install -v .` and tested using the import `from pettingzoo.magent import battle_v3`. 

Fixes #5

Tested Architecture:
- Apple M1
- macOS 12.3.1
- Python 3.8.12

### CODE REVIEW

**Comment by jkterry1** [comment]
Can you please look into the test failures?

**Comment by dsctt** [comment]
@corentinartaud Can you also test the following code on each architecture? It should pop up a small pygame window and show agents moving around, at which point you can exit. We were working on this before and had an issue with the window popping up on m1, but that may have had an unrelated cause. 

```from pettingzoo.magent import battle_v3
from pettingzoo.utils import random_demo

env = battle_v3.env(map_size=20, minimap_mode=False, step_reward=-0.005,
                    dead_penalty=-0.1, attack_penalty=-0.1, attack_opponent_reward=0.2,
                    max_cycles=100000, extra_features=False)
env.reset()
random_demo(env, render=True, episodes=1)```

**Comment by dsctt** [comment]
We deployed a test package of this PR and it failed to install on an m1 mac. Previously, we did the same with basically these settings but removing the whole `IF (APPLE)` section of the CMakeLists and it installed. That's how we got as far as what's in my last comment--the test script running but no window popup.

**Comment by jkterry1** [comment]
Closed in favor of https://github.com/Farama-Foundation/MAgent/pull/15

**Pull request closed without merging**
